### ISSUE TITLE
Migrations fail

### ISSUE THREAD

**Issue by jhintringer** [leafsphp/leafAPI#15]
(Duplicate Issue from https://github.com/leafsphp/leaf/issues/54)

Hy there. I can't get Migrations running with LeafAPI. It always breaks with error on line 14 (var capsule is invalid).
`php leaf db:install` worked and the database was created successfully.
`php leaf db:migrate` fails.

![leaf_db_migrate_error_capsule](https://user-images.githubusercontent.com/9859818/134201535-fdba1541-167f-4127-a1a7-55a365432291.jpg)

Can you help me with this? Thanks a lot!

Versions, i'm using:
- PHP 8
- Leaf 2.6.0
- Aloe 1.1.0

**Edit//**
It seems to be related to last commit https://github.com/leafsphp/leaf/commit/0ca6097f63b561199272765f3a2b625d0f516857
Maybe a dependency conflict?

**Comment by Aminur670** [comment]
Sorry, but we found same new issue. I think they are still updating this section in better way.
![image](https://user-images.githubusercontent.com/32174602/137218000-cd459294-5c26-4c08-a62d-01c8d33c5c7e.png)

**Comment by nickelnext** [comment]
The only way to get it working is downloading the MVC app, remove the SCHEMA (which reads from the json, which has WRONG properties) and uncomment the php lines that create the db.

After that, you can install the leafsAPI

**Comment by mychidarko** [comment]
This problem was due to an update in Leaf MVC core, Leaf MVC has already received an update, Leaf API is scheduled to receive one today. In the meantime, you can manually update Aloe CLI by running this command `composer require leafs/aloe`.

You will also need to update your existing migrations to use the static capsule from leaf mvc core

```php
if (!static::$capsule::schema()->hasTable("users")):
  static::$capsule::schema()->create("users", function (Blueprint $table) {
    $table->increments('id');
    $table->string('username');
    $table->string('name');
    $table->string('email')->unique();
    $table->timestamp('email_verified_at')->nullable();
    $table->string('password');
    $table->rememberToken();
    $table->timestamps();
  });
endif;
```

**Comment by mychidarko** [comment]
@jhintringer your issue was caused by a different problem though, that's the absence of the db_charset and db_collation env variables

DB_CHARSET=utf8
DB_COLLATION=utf8_unicode_ci

**Comment by mychidarko** [comment]
As promised, the update for Leaf API has just been published, you can now update to v2.2.

A few things to note, global functions `json`, `markup`, `requestData` and `requestBody` are no longer supported, you now need to use `response()->json()`, `response()->markup`, `request()->get` and `request()->body` respectively.

Note that `request` and `response` work just as they have in earlier versions.

```php
response(["something" => "value"]);

// is the same as

response()->json(["something" => "value"]);
```

**Comment by nickelnext** [comment]
Thank you for your update.

I want to point out that also some of the comments in the code were outdated.

Ie: if I create a controller exactly like the UserController already present in the project, by using the CLI, the 

`$this->auth` does not exists.

Is that because the templating system doesn't work for some reason?. I had to use the static class `Auth::id` to check if the user is logged. While the template says to use `$this`

**Comment by mychidarko** [comment]
Hi @nickelnext, thanks for pointing out the comments and auth feature. All of those have been fixed now.
